# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: local
    hooks:
    -   id: trailing-whitespace-fixer
        name: trailing-whitespace-fixer
        entry: trailing-whitespace-fixer
        language: system
        types: [ python ]

    -   id: end-of-file-fixer
        name: end-of-file-fixer
        entry: end-of-file-fixer
        language: system
        types: [ python ]

    -   id: check-added-large-files
        name: check-added-large-files
        entry: check-added-large-files
        language: system
        types: [ python ]

-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black
        language: system
        types: [python]

-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: ["--max-line-length=110",]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: ["--ignore-missing-imports",]
