"""db structure update

Revision ID: 2d147528fe02
Revises: c5e26242be17
Create Date: 2021-12-28 15:16:12.717920

"""
from alembic import op  # noqa
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision = "2d147528fe02"
down_revision = "c5e26242be17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
