"""initial commit

Revision ID: 3663470c5088
Revises: 
Create Date: 2021-12-22 23:19:31.234366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3663470c5088"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book")
    # ### end Alembic commands ###
